
CREATE TABLE POSITION
(PositionID int PRIMARY KEY NOT NULL,
PositionTitle varchar(50) NOT NULL, 
EmployerID varchar(5) NOT NULL,
Wage Money NOT NULL,
HoursPerWeek int,
Experience bit,
Openings int,
CONSTRAINT FK_EMP_ID FOREIGN KEY (EmployerID)
REFERENCES EMPLOYER (EmployerID),
);
GO


CREATE TABLE EMPLOYER
(	EmployerID 		varchar(5) PRIMARY KEY NOT NULL,
	EmployerName 	varchar(50) NOT NULL,
	StreetAddress 		varchar(50),
	City 			varchar(50),
	StateProv 		varchar(2),
	PostalCode 		varchar(7),
	Country 		varchar(50),
	ContactFirstName 	varchar(50),
	ContactLastName 	varchar(50),
	Position 		varchar(50),
	Phone 			varchar(10),
	Website 		bit,
	NAICSCode 		varchar(6) NOT NULL,
CONSTRAINT FK_NAICS_CODE FOREIGN KEY (NAICSCode)
REFERENCES NAICS (NAICSCode),
CONSTRAINT FK_State_Prov FOREIGN KEY (StateProv)
REFERENCES LOCATION (Abv),
);
GO	

CREATE TABLE NAICS
(NAICSCode 		varchar(6) PRIMARY KEY NOT NULL,
NAICSDesc 		varchar(50));
GO

CREATE TABLE LOCATION
(Abv 			varchar(2) PRIMARY KEY NOT NULL,	
Location 		varchar(50),
);
GO

SELECT * FROM LOCATION;
SELECT * FROM NAICS;
SELECT * FROM EMPLOYER;
SELECT * FROM POSITION;

ALTER TABLE POSITION 
ADD TOTALOPENINGS AS EXPERIENCE * OPENINGS;

SELECT SUM(TOTALOPENINGS) FROM POSITION;

SELECT * FROM
(SELECT EMPLOYER.*
FROM EMPLOYER
INNER JOIN NAICS ON EMPLOYER.NAICSCode = NAICS.NAICSCode	
WHERE EMPLOYER.NAICSCode = '72111'
) STATES;

SELECT StateProv, Sum(Openings)
FROM
(SELECT EMPLOYER.*, EMPLOYER.EmployerID, POSITION.Openings
FROM EMPLOYER
INNER JOIN POSITION ON POSITION.EmployerID = EMPLOYER.EmployerID;
GROUP BY StateProv;

SELECT EMPLOYER.StateProv, LOCATION.Location, SUM(Position.Openings) Openings FROM POSITION
INNER JOIN EMPLOYER ON POSITION.EmployerID = EMPLOYER.EmployerID
INNER JOIN NAICS ON NAICS.NAICSCode = EMPLOYER.NAICSCode
INNER JOIN LOCATION ON LOCATION.Abv = EMPLOYER.StateProv
WHERE NAICS.NAICSCode = 'Hotels and Motels'
GROUP BY EMPLOYER.StateProv, LOCATION ORDER BY Openings DESC;

SELECT Abv, Location FROM
(SELECT LOCATION.Abv, LOCATION.Location, SUM(POSITION.Openings) NumOp,
SUM(POSITION.Experience*POSITION.Openings) OpEx
FROM EMPLOYER
INNER JOIN LOCATION ON EMPLOYER.StateProv = LOCATION.Abv
INNER JOIN POSITION ON EMPLOYER.EmployerID = POSITION.EmployerID
GROUP BY Abv, Location) a
WHERE NumOp >= 25 AND OpEx >= 10;

SELECT Abv, Location FROM LOCATION
LEFT OUTER JOIN EMPLOYER ON LOCATION.Abv = EMPLOYER.StateProv
WHERE StateProv IS NULL;

SELECT LOCATION.Abv, LOCATION.Location FROM EMPLOYER
INNER JOIN NAICS ON NAICS.NAICSCode = EMPLOYER.NAICSCode
INNER JOIN LOCATION ON LOCATION.Abv = EMPLOYER.StateProv
INNER JOIN POSITION ON POSITION.EmployerID = EMPLOYER.EmployerID
WHERE NAICS.NAICSCode = 'Hotels and Motels'
AND POSITION.Openings > 0
AND POSITION.Experience > 0
GROUP BY LOCATION.Abv, LOCATION.Location;

SELECT a.StateProv, a.Location FROM
(SELECT EMPLOYER.StateProv, LOCATION.Location, POSITION.Experience, SUM(POSITION.Openings) as NumOp
FROM EMPLOYER
INNER JOIN NAICS ON NAICS.NAICSCode = EMPLOYER.NAICSCode
INNER JOIN LOCATION ON LOCATION.Abv = EMPLOYER.StateProv
INNER JOIN POSITION ON POSITION.EmployerID = EMPLOYER.EmployerID
WHERE NAICS.NAICSCode = 'Hotels and Motels'
GROUP BY StateProv, Location, Experience) a
WHERE NOT EXISTS(SELECT a.StateProv, a.Location
WHERE a.Experience = 1);